package ie.ul.csis.cs4135.pcshop;

public enum ProductsEnum {
	COMPUTER_DESKTOP_GAMING,
	COMPUTER_DESKTOP_OFFICE,
	COMPUTER_DESKTOP_HOME,
	COMPUTER_LAPTOP_ULTRAMOBILE,
	COMPUTER_LAPTOP_OFFICE,
	COMPUTER_LAPTOP_GAMING

}
