package simple;

public class SimpleGUI2 extends javax.swing.JPanel {
	SimpleGUI1 parent;

    public SimpleGUI2(SimpleGUI1 parentWindow) {
        initComponents();
        parent = parentWindow;
        parent.setTotalLabel(111.1F);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        computerCorpLabel = new javax.swing.JLabel();
        customerDetailLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerDetailsTextbox = new javax.swing.JTextArea();
        orderMgrLabel = new javax.swing.JLabel();
        upperSeparator = new javax.swing.JSeparator();
        selectProductLabel = new javax.swing.JLabel();
        productTypeCombobox = new javax.swing.JComboBox();
        monitorLabel = new javax.swing.JLabel();
        KeyboardLabel = new javax.swing.JLabel();
        speakersLabel = new javax.swing.JLabel();
        chassisLabel = new javax.swing.JLabel();
        hardDiskLabel = new javax.swing.JLabel();
        psuLabel = new javax.swing.JLabel();
        moboLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        addProductBtn = new javax.swing.JButton();
        cpuLabel = new javax.swing.JLabel();
        gpuLabel = new javax.swing.JLabel();
        ramLabel = new javax.swing.JLabel();
        monitorValueLabel = new javax.swing.JLabel();
        KeyboardValueLabel = new javax.swing.JLabel();
        speakersValueLabel = new javax.swing.JLabel();
        chassisValueLabel = new javax.swing.JLabel();
        hardDiskValueLabel = new javax.swing.JLabel();
        psuValueLabel = new javax.swing.JLabel();
        moboValueLabel = new javax.swing.JLabel();
        cpuValueLabel = new javax.swing.JLabel();
        gpuValueLabel = new javax.swing.JLabel();
        ramValueLabel = new javax.swing.JLabel();
        dvdLabel = new javax.swing.JLabel();
        dvdValueLabel = new javax.swing.JLabel();
        addMonitorBtn = new javax.swing.JButton();
        addKeyboardBtn = new javax.swing.JButton();
        addSpeakersBtn = new javax.swing.JButton();
        addChassisBtn = new javax.swing.JButton();
        addHardDiskBtn = new javax.swing.JButton();
        addPsuBtn = new javax.swing.JButton();
        addDVDBtn = new javax.swing.JButton();
        addMoboBtn = new javax.swing.JButton();
        addCpuBtn = new javax.swing.JButton();
        addGpuBtn = new javax.swing.JButton();
        addRamBtn = new javax.swing.JButton();
        clearMonitorBtn = new javax.swing.JButton();
        clearKeyboardBtn = new javax.swing.JButton();
        clearSpeakersBtn = new javax.swing.JButton();
        clearHardDiskBtn = new javax.swing.JButton();
        clearPsuBtn = new javax.swing.JButton();
        clearChassiaBtn = new javax.swing.JButton();
        clearMoboBtn = new javax.swing.JButton();
        clearCpuBtn = new javax.swing.JButton();
        clearDVDBtn = new javax.swing.JButton();
        clearRamBtn = new javax.swing.JButton();
        clearGpuBtn = new javax.swing.JButton();
        monitorCounterLabel = new javax.swing.JLabel();
        keyboardCounterLabel = new javax.swing.JLabel();
        speakersCounterLabel = new javax.swing.JLabel();
        chassisCounterLabel = new javax.swing.JLabel();
        hardDiskCounterLabel = new javax.swing.JLabel();
        psuCounterLabel = new javax.swing.JLabel();
        DVDCounterLabel = new javax.swing.JLabel();
        moboCounterLabel = new javax.swing.JLabel();
        cpuCounterLabel = new javax.swing.JLabel();
        gpuCounterLabel = new javax.swing.JLabel();
        ramCounterLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        totalCostValueLabel = new javax.swing.JLabel();
        totalCostLabel = new javax.swing.JLabel();

        computerCorpLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        computerCorpLabel.setText("Computer Corp");

        customerDetailLabel.setText("CustomerDetails");

        customerDetailsTextbox.setColumns(20);
        customerDetailsTextbox.setRows(5);
        jScrollPane1.setViewportView(customerDetailsTextbox);

        orderMgrLabel.setText("Order Manager:");

        selectProductLabel.setText("Select Product Type");

        productTypeCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productTypeCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTypeComboboxActionPerformed(evt);
            }
        });

        monitorLabel.setText("Monitor:");

        KeyboardLabel.setText("Keyboard:");

        speakersLabel.setText("Speakers:");

        chassisLabel.setText("Chassis:");

        hardDiskLabel.setText("Hard Disk:");

        psuLabel.setText("Power Supply:");

        moboLabel.setText("Motherboard:");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addProductBtn.setText("Add a Product");
        addProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductBtnActionPerformed(evt);
            }
        });

        cpuLabel.setText("CPU:");

        gpuLabel.setText("GPU:");

        ramLabel.setText("RAM:");

        monitorValueLabel.setText("100.00");

        KeyboardValueLabel.setText("100.00");

        speakersValueLabel.setText("100.00");

        chassisValueLabel.setText("100.00");

        hardDiskValueLabel.setText("100.00");

        psuValueLabel.setText("100.00");

        moboValueLabel.setText("100.00");

        cpuValueLabel.setText("100.00");

        gpuValueLabel.setText("100.00");

        ramValueLabel.setText("100.00");

        dvdLabel.setText("DVD:");

        dvdValueLabel.setText("100.00");

        addMonitorBtn.setText("+");
        addMonitorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMonitorBtnActionPerformed(evt);
            }
        });

        addKeyboardBtn.setText("+");
        addKeyboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addKeyboardBtnActionPerformed(evt);
            }
        });

        addSpeakersBtn.setText("+");
        addSpeakersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSpeakersBtnActionPerformed(evt);
            }
        });

        addChassisBtn.setText("+");
        addChassisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChassisBtnActionPerformed(evt);
            }
        });

        addHardDiskBtn.setText("+");
        addHardDiskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHardDiskBtnActionPerformed(evt);
            }
        });

        addPsuBtn.setText("+");
        addPsuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPsuBtnActionPerformed(evt);
            }
        });

        addDVDBtn.setText("+");
        addDVDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDVDBtnActionPerformed(evt);
            }
        });

        addMoboBtn.setText("+");
        addMoboBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoboBtnActionPerformed(evt);
            }
        });

        addCpuBtn.setText("+");
        addCpuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpuBtnActionPerformed(evt);
            }
        });

        addGpuBtn.setText("+");
        addGpuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGpuBtnActionPerformed(evt);
            }
        });

        addRamBtn.setText("+");
        addRamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRamBtnActionPerformed(evt);
            }
        });

        clearMonitorBtn.setText("-");
        clearMonitorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMonitorBtnActionPerformed(evt);
            }
        });

        clearKeyboardBtn.setText("-");
        clearKeyboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearKeyboardBtnActionPerformed(evt);
            }
        });

        clearSpeakersBtn.setText("-");
        clearSpeakersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSpeakersBtnActionPerformed(evt);
            }
        });

        clearHardDiskBtn.setText("-");
        clearHardDiskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearHardDiskBtnActionPerformed(evt);
            }
        });

        clearPsuBtn.setText("-");
        clearPsuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPsuBtnActionPerformed(evt);
            }
        });

        clearChassiaBtn.setText("-");
        clearChassiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearChassiaBtnActionPerformed(evt);
            }
        });

        clearMoboBtn.setText("-");
        clearMoboBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMoboBtnActionPerformed(evt);
            }
        });

        clearCpuBtn.setText("-");
        clearCpuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCpuBtnActionPerformed(evt);
            }
        });

        clearDVDBtn.setText("-");
        clearDVDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDVDBtnActionPerformed(evt);
            }
        });

        clearRamBtn.setText("-");
        clearRamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearRamBtnActionPerformed(evt);
            }
        });

        clearGpuBtn.setText("-");
        clearGpuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearGpuBtnActionPerformed(evt);
            }
        });

        monitorCounterLabel.setText("jLabel1");

        keyboardCounterLabel.setText("jLabel2");

        speakersCounterLabel.setText("jLabel3");

        chassisCounterLabel.setText("jLabel4");

        hardDiskCounterLabel.setText("jLabel5");

        psuCounterLabel.setText("jLabel6");

        DVDCounterLabel.setText("jLabel7");

        moboCounterLabel.setText("jLabel8");

        cpuCounterLabel.setText("jLabel9");

        gpuCounterLabel.setText("jLabel10");

        ramCounterLabel.setText("jLabel11");

        totalCostValueLabel.setText("jLabel1");

        totalCostLabel.setText("Total Cost:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(computerCorpLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(selectProductLabel)
                                .addComponent(orderMgrLabel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(customerDetailLabel)
                                        .addGap(238, 238, 238))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(productTypeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(upperSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(monitorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(monitorValueLabel)
                                .addGap(27, 27, 27)
                                .addComponent(addMonitorBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KeyboardLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(KeyboardValueLabel)
                                .addGap(27, 27, 27)
                                .addComponent(addKeyboardBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(speakersLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(speakersValueLabel)
                                .addGap(27, 27, 27)
                                .addComponent(addSpeakersBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chassisLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(chassisValueLabel)
                                .addGap(27, 27, 27)
                                .addComponent(addChassisBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hardDiskLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(hardDiskValueLabel)
                                .addGap(27, 27, 27)
                                .addComponent(addHardDiskBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(psuLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(psuValueLabel)
                                .addGap(27, 27, 27)
                                .addComponent(addPsuBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dvdLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                .addComponent(dvdValueLabel)
                                .addGap(27, 27, 27)
                                .addComponent(addDVDBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(moboLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(moboValueLabel)
                                .addGap(27, 27, 27)
                                .addComponent(addMoboBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpuLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                .addComponent(cpuValueLabel)
                                .addGap(27, 27, 27)
                                .addComponent(addCpuBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gpuLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                .addComponent(gpuValueLabel)
                                .addGap(27, 27, 27)
                                .addComponent(addGpuBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ramLabel)
                                    .addComponent(totalCostLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalCostValueLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ramValueLabel)
                                        .addGap(27, 27, 27)
                                        .addComponent(addRamBtn)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearRamBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(clearKeyboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(clearMonitorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(clearSpeakersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(clearChassiaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(clearHardDiskBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(clearPsuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(clearDVDBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(clearMoboBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(clearCpuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(clearGpuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monitorCounterLabel)
                            .addComponent(keyboardCounterLabel)
                            .addComponent(speakersCounterLabel)
                            .addComponent(chassisCounterLabel)
                            .addComponent(hardDiskCounterLabel)
                            .addComponent(psuCounterLabel)
                            .addComponent(DVDCounterLabel)
                            .addComponent(moboCounterLabel)
                            .addComponent(cpuCounterLabel)
                            .addComponent(gpuCounterLabel)
                            .addComponent(ramCounterLabel))
                        .addGap(302, 302, 302))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 465, Short.MAX_VALUE)
                        .addComponent(addProductBtn)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(computerCorpLabel)
                    .addComponent(customerDetailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderMgrLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectProductLabel)
                    .addComponent(productTypeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(upperSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monitorLabel)
                            .addComponent(monitorValueLabel)
                            .addComponent(addMonitorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(KeyboardValueLabel)
                                .addComponent(addKeyboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(KeyboardLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(speakersValueLabel)
                                .addComponent(addSpeakersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(speakersLabel))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chassisValueLabel)
                                .addComponent(addChassisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chassisLabel))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hardDiskValueLabel)
                                .addComponent(addHardDiskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hardDiskLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(psuValueLabel)
                                .addComponent(addPsuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(psuLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dvdValueLabel)
                                .addComponent(addDVDBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dvdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(moboValueLabel)
                                .addComponent(addMoboBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(moboLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cpuValueLabel)
                                .addComponent(addCpuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cpuLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gpuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(gpuValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addGpuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ramValueLabel)
                            .addComponent(ramLabel)
                            .addComponent(addRamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearRamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ramCounterLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearMonitorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monitorCounterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearKeyboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(keyboardCounterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearSpeakersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(speakersCounterLabel))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearChassiaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chassisCounterLabel))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearHardDiskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hardDiskCounterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearPsuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(psuCounterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearDVDBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DVDCounterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearMoboBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moboCounterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearCpuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpuCounterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearGpuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gpuCounterLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCostValueLabel)
                    .addComponent(totalCostLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(addProductBtn))
                .addContainerGap())
        );
    }// </editor-fold>

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addMonitorBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addKeyboardBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addSpeakersBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addChassisBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addHardDiskBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addPsuBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addDVDBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addMoboBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addCpuBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addGpuBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addRamBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clearMonitorBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clearKeyboardBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clearSpeakersBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clearHardDiskBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clearPsuBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clearChassiaBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clearMoboBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clearCpuBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clearDVDBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clearRamBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clearGpuBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addProductBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void productTypeComboboxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel DVDCounterLabel;
    private javax.swing.JLabel KeyboardLabel;
    private javax.swing.JLabel KeyboardValueLabel;
    private javax.swing.JButton addChassisBtn;
    private javax.swing.JButton addCpuBtn;
    private javax.swing.JButton addDVDBtn;
    private javax.swing.JButton addGpuBtn;
    private javax.swing.JButton addHardDiskBtn;
    private javax.swing.JButton addKeyboardBtn;
    private javax.swing.JButton addMoboBtn;
    private javax.swing.JButton addMonitorBtn;
    private javax.swing.JButton addProductBtn;
    private javax.swing.JButton addPsuBtn;
    private javax.swing.JButton addRamBtn;
    private javax.swing.JButton addSpeakersBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel chassisCounterLabel;
    private javax.swing.JLabel chassisLabel;
    private javax.swing.JLabel chassisValueLabel;
    private javax.swing.JButton clearChassiaBtn;
    private javax.swing.JButton clearCpuBtn;
    private javax.swing.JButton clearDVDBtn;
    private javax.swing.JButton clearGpuBtn;
    private javax.swing.JButton clearHardDiskBtn;
    private javax.swing.JButton clearKeyboardBtn;
    private javax.swing.JButton clearMoboBtn;
    private javax.swing.JButton clearMonitorBtn;
    private javax.swing.JButton clearPsuBtn;
    private javax.swing.JButton clearRamBtn;
    private javax.swing.JButton clearSpeakersBtn;
    private javax.swing.JLabel computerCorpLabel;
    private javax.swing.JLabel cpuCounterLabel;
    private javax.swing.JLabel cpuLabel;
    private javax.swing.JLabel cpuValueLabel;
    private javax.swing.JLabel customerDetailLabel;
    private javax.swing.JTextArea customerDetailsTextbox;
    private javax.swing.JLabel dvdLabel;
    private javax.swing.JLabel dvdValueLabel;
    private javax.swing.JLabel gpuCounterLabel;
    private javax.swing.JLabel gpuLabel;
    private javax.swing.JLabel gpuValueLabel;
    private javax.swing.JLabel hardDiskCounterLabel;
    private javax.swing.JLabel hardDiskLabel;
    private javax.swing.JLabel hardDiskValueLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel keyboardCounterLabel;
    private javax.swing.JLabel moboCounterLabel;
    private javax.swing.JLabel moboLabel;
    private javax.swing.JLabel moboValueLabel;
    private javax.swing.JLabel monitorCounterLabel;
    private javax.swing.JLabel monitorLabel;
    private javax.swing.JLabel monitorValueLabel;
    private javax.swing.JLabel orderMgrLabel;
    private javax.swing.JComboBox productTypeCombobox;
    private javax.swing.JLabel psuCounterLabel;
    private javax.swing.JLabel psuLabel;
    private javax.swing.JLabel psuValueLabel;
    private javax.swing.JLabel ramCounterLabel;
    private javax.swing.JLabel ramLabel;
    private javax.swing.JLabel ramValueLabel;
    private javax.swing.JLabel selectProductLabel;
    private javax.swing.JLabel speakersCounterLabel;
    private javax.swing.JLabel speakersLabel;
    private javax.swing.JLabel speakersValueLabel;
    private javax.swing.JLabel totalCostLabel;
    private javax.swing.JLabel totalCostValueLabel;
    private javax.swing.JSeparator upperSeparator;
    // End of variables declaration

}
